#ifndef DRIVER_H
#define DRIVER_H
#define NUM_OF_TERMINALS 61
#define MAX_SYMBOL_LENGTH 50
#define NUM_OF_NONTERMINALS 53

char keyToToken[NUM_OF_TERMINALS][MAX_SYMBOL_LENGTH];
char keyToNT[NUM_OF_NONTERMINALS][MAX_SYMBOL_LENGTH];

#endif
