#ifndef DRIVER_H
#define DRIVER_H
#define NUM_OF_TERMINALS 60
#define MAX_SYMBOL_LENGTH 50
#define NUM_OF_NONTERMINALS 51

char keyToToken[NUM_OF_TERMINALS][MAX_SYMBOL_LENGTH];
char keyToNT[NUM_OF_NONTERMINALS][MAX_SYMBOL_LENGTH];

#endif
